// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package models

import (
	"database/sql"
)

type Partner struct {
	ID          sql.NullInt64 `db:"id"`
	Servicename string        `db:"servicename"`
	Latitude    float64       `db:"latitude"`
	Longitude   float64       `db:"longitude"`
	Radius      int32         `db:"radius"`
}
