// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package models

import ()

type Partner struct {
	ID          int64   `db:"id"`
	Partnername string  `db:"partnername"`
	Servicename string  `db:"servicename"`
	Latitude    float64 `db:"latitude"`
	Longitude   float64 `db:"longitude"`
	Material    string  `db:"material"`
	Radius      int32   `db:"radius"`
	Rating      float64 `db:"rating"`
}
